### ISSUE TITLE
Auto-update match scores and teams

### ISSUE THREAD

**Issue by syxolk** [syxolk/euro2024#49]
Some people requested to get automatic score updates for the Euro 2016, see here: #16 

- [football-data.org](https://www.football-data.org/) looks quite promising: http://api.football-data.org/v1/competitions/467
- [openfooty](http://www.footytube.com/openfooty/api_overview.php) might be interesting as well but their API server is down?!

**Comment by mnanu** [comment]
hi! i think i solved this, but i can't upload my changes.
git push -u origin issue-49
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
remote: Permission to syxolk/euro2016.git denied

**Comment by syxolk** [comment]
Thanks! You have to fork my repository, push your branch to the fork and then create a pull request.

**Comment by mnanu** [comment]
yes, i figure that after i posted the comment :smile:  see pull request #60

**Comment by syxolk** [comment]
For the last world cup I implemented this using FIFA's own (internal) API: https://api.fifa.com/api/v3/calendar/matches?count=100&idSeason=255711

For this Euro 2204, I will use UEFA's own API: https://match.uefa.com/v5/matches?competitionId=3&offset=0&limit=51
However, this is not yet implemented.
