### ISSUE TITLE
Updated score?

### ISSUE THREAD

**Issue by CyrilNb** [syxolk/euro2024#82]
is there any chance that the "tools/euro2024/euro2024.json" will be updated with scores?

**Comment by syxolk** [comment]
Hey, thanks for asking. I will not update this particular file but I will fix this endpoint https://github.com/syxolk/euro2024/blob/master/routes/autoupdate_match_result.js which will set the match results automatically.

I'm planning to use this inofficial UEFA API: https://match.uefa.com/v5/matches?competitionId=3&offset=0&limit=51

**Comment by CyrilNb** [comment]
Thanks for letting me know!

**Comment by xHeler** [comment]
So, how to update match result right now ?

**Comment by syxolk** [comment]
> So, how to update match result right now ?

You can set the `admin` column to true for your own `user_account` in the database. Then you will be able to access this page:

![grafik](https://github.com/syxolk/euro2024/assets/6666063/6e641dc2-b57a-4d4b-bf5d-811444d37d8a)

**Comment by xHeler** [comment]
I just write it by own using UEFA API here. @CyrilNb  check it, if you want to use.
https://github.com/xHeler/euro2024/tree/auto-match-results

@syxolk Check my PR:
https://github.com/syxolk/euro2024/pull/83

Tomorrow I also add auto update teams.

**Comment by syxolk** [comment]
Auto-updating the score works now, thanks to @xHeler !
