### ISSUE TITLE
Finish extra bets feature

### ISSUE THREAD

**Issue by syxolk** [syxolk/euro2024#86]
What we already have:
- users can see and edit their own extra bets
- list of all extra bets

What is missing:
- computation of extra bet score for highscore table
- admin panel: set/edit extra bet result
- show extra bet on user page

**Comment by matebenyovszky** [comment]
Thank you! Is there a way to trigger for recalculations of extra bats? We have updated the application more then an hour ago in our docker environment, but the extra bet points is not yet updated. Thanks in advance, out colleagues are loving the app!

**Comment by syxolk** [comment]
When you have a user with the `is_admin` column set to true, you can go to the admin panel and set the extra bets manually:

![image](https://github.com/user-attachments/assets/6a4764d2-8f67-498e-be35-4c130f25299f)

**Comment by matebenyovszky** [comment]
![image](https://github.com/user-attachments/assets/482e9758-0e39-4aa8-99dd-d7c988b9a3cc)

Users already have placed their bets, but it is not calculated. Do you mean we should login in with the admin and manually update every single users' extra bets?

**Comment by syxolk** [comment]
No, you just have to set the result of the extra bet once, not for every user. I didn't implement an automation for it.

**Comment by matebenyovszky** [comment]
Thank you, the problem is now solved :) 🙏
Best wishes!
